# Generated by Django 5.2 on 2025-04-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='МестаВЗале',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('номер_места', models.PositiveIntegerField(unique=True, verbose_name='Номер места')),
            ],
            options={
                'verbose_name': 'Место в зале',
                'verbose_name_plural': 'Места в зале',
                'ordering': ['номер_места'],
            },
        ),
        migrations.CreateModel(
            name='СеансыФильмов',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название_фильма', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('время_начала', models.DateTimeField(verbose_name='Время начала')),
                ('время_окончания', models.DateTimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Сеанс фильма',
                'verbose_name_plural': 'Сеансы фильмов',
                'ordering': ['время_начала'],
            },
        ),
        migrations.CreateModel(
            name='ФизическиеЛица',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('фамилия', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('имя', models.CharField(max_length=100, verbose_name='Имя')),
                ('отчество', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('номер_телефона', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('дата_рождения', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
                'ordering': ['фамилия', 'имя'],
            },
        ),
        migrations.CreateModel(
            name='КупленныеБилеты',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_покупки', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('pdf_файл', models.FileField(blank=True, null=True, upload_to='tickets/', verbose_name='PDF Билет')),
                ('место', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_tickets.меставзале', verbose_name='Место')),
                ('сеанс', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_tickets.сеансыфильмов', verbose_name='Сеанс')),
                ('клиент', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_tickets.физическиелица', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Купленный билет',
                'verbose_name_plural': 'Купленные билеты',
                'ordering': ['-дата_покупки'],
                'unique_together': {('сеанс', 'место')},
            },
        ),
    ]
