# Generated by Django 5.2 on 2025-04-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='купленныебилеты',
            name='email_получателя',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email получателя при покупке'),
        ),
        migrations.AddField(
            model_name='физическиелица',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
